services:
  templateangular:
    container_name: angularcontainer
    image: templateangular
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:80

  templateangular-tests:
    container_name: angular-test
    image: cypress/browsers:node-22.17.0-chrome-138.0.7204.92-1-ff-140.0.2-edge-138.0.3351.65-1
    working_dir: /app
    volumes:
      - .:/app
    environment:
      CHROME_BIN: /usr/bin/google-chrome
    entrypoint: ["npm", "run", "test", "--"]
