services:
  templateangular:
    container_name: angularcontainer
    image: templateangular
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
